# Site settings
title: Panela de Pau
email: mariana.cs@live.com
description: Blog de culinária feito à base de espontaneidade e descontração.
baseurl: http://paneladepau.com.br
github_username:  PaneladePau

# Build settings
markdown: rdiscount
destination: ./_site
permalink: /:title
exclude: ['Gemfile','Gemfile.lock','_posts/aaaa-mm-dd-titulo-do-post.md']
paginate: 9
paginate_path: "pagina-:num"
highlighter: rouge
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "post"
      published: "true"

# Plugins
gems:
- jekyll-sitemap